# Generated by Django 3.2.7 on 2021-09-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepis', '0002_rename_receitas_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.CharField(max_length=50),
        ),
    ]
